layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

 social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
   instagram: ajlord18
  # keybase: your_username
   linkedin: ajsanjoaquin
  # mastodon: your_username
   medium: ajsanjoaquin
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username


topics:
  - name: Historical Trivia
    web_url: https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire
    image_url: https://img-9gag-fun.9cache.com/photo/amBypO6_700bwp.webp

  - name: Cycling

  - name: Philosophy
    web_url: https://www.iep.utm.edu/consciou/
    image_url: https://i.pinimg.com/originals/b6/e6/ec/b6e6ec61a6e233194d64dbecef169c9f.jpg
